### PR TITLE
Alter when accessor methods are generated.

### LINKED ISSUE #89: Method reference to protected method in base class in other package fails with IllegalAccessError
A method reference to protected method in base class in other package fails with java.lang.IllegalAccessError at runtime.

Probably since it is called from a generated inner class which is not a subclass of the base class, and therefore cannot access the protected method the base class in other package.
`
java.lang.IllegalAccessError: Method 'void com.foo.common.BaseClass.someMethod()' is inaccessible to class 'com.foo.stuff.Subclass$$Lambda$3'`

com.foo.stuff.Subclass extends com.foo.common.BaseClass.

### PR DESCRIPTION
**Pull request by JakeWharton**
Refs #81 item 1. This removes 561 methods from our app.

Closes #89.

### CODE REVIEW

File: retrolambda/src/main/java/net/orfjackal/retrolambda/interfaces/ClassAnalyzer.java [hunk 1]
```diff
@@ -45,10 +45,16 @@ public void visit(int version, int access, String name, String signature, String
 
             @Override
             public MethodVisitor visitMethod(int access, String name, String desc, String signature, String[] exceptions) {
-                if (isConstructor(name) || isStaticMethod(access)) {
```
Comment (JakeWharton) [inline retrolambda/src/main/java/net/orfjackal/retrolambda/interfaces/ClassAnalyzer.java]: Having the static methods is the mechanism through which I'm going to implement point 2 on #81. By having a list of the private static methods which are synthetic and looking at invokedynamic's to those methods we can remove the private bit on the static method and skip the accessor.

**Comment by JakeWharton** [comment]
I have updated this to address #89 as well.
